services:
 mysql-db:
    image: mysql:latest # Specify MySQL version here
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: M295_LB_Projekt
      MYSQL_USER: jan
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data_1:/var/lib/mysql
    ports:
      - "3306:3306" # Expose MySQL on the default port

volumes:
  mysql-data_1:

